# Generated by Django 2.1 on 2019-01-03 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=300, verbose_name='项目名称')),
                ('tester', models.CharField(max_length=300, verbose_name='测试人员')),
                ('developer', models.CharField(max_length=300, verbose_name='开发人员')),
                ('receive_mail', models.CharField(max_length=300, verbose_name='接收报警邮件邮箱地址')),
                ('dingding', models.CharField(max_length=300, verbose_name='钉钉机器人地址')),
                ('pro_detail', models.TextField(verbose_name='项目描述')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
            },
        ),
    ]
